# Generated by Django 2.1.3 on 2019-02-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstclinicapp', '0002_auto_20190208_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')])),
                ('notes', models.CharField(max_length=500)),
            ],
        ),
    ]
